### PR TITLE
Fixed issue #2

### PR DESCRIPTION
**Pull request by ankushKun**
Was missing an `elif` in line 88 that caused that error in issue #2.
Filtered streams to only download .mp4 and .mp3 files.
Added a print statement before downloading to let the user know it is downloading since there was no such message.
Put welcome in a single line

### CODE REVIEW

**Comment by ankushKun** [comment]
@joelubuntu Hi, the hacktoberfest label you added has a typo in it, it should be `Hacktoberfest` not `Hactoberfest`.
Could you please fix it ASAP.

Thank you :)

**Comment by joelubuntu** [comment]
done!

**Comment by ankushKun** [comment]
Thanks :D

**Comment by ankushKun** [comment]
@joelubuntu Could you also add the Hacktoberfest topic to the repository because without that my PR wont be counted.
or you can add another `Hacktoberfest-accepted` label to this PR 😬

**Pull request merged**
